from pylogics.parsers import parse_pltl
parse_pltl("tt")
parse_pltl("ff")
parse_pltl("true")
parse_pltl("false")
parse_pltl("a")
parse_pltl("b")
parse_pltl("O(b)")
a = parse_pltl("Z(b)")
parse_pltl("Z(b)")
parse_pltl("H(a)")
parse_pltl("a S b")
parse_pltl("a T b")
parse_pltl("Z(a)")
